services:
  # hammerdb:   # Not support arm64
  #   image: tpcorg/hammerdb:latest
  #   container_name: hammerdb
  #   stdin_open: true
  #   tty: true
  #   platform: linux/arm64

  tidb:
    image: pingcap/tidb:latest
    container_name: tidb
    ports:
      - "4000:4000"
    environment:
      - TIDB_ADVERTISE_ADDRESS=tidb
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=sbtest
      - MYSQL_USER=sbtest
      - MYSQL_PASSWORD=password

  pd:
    image: pingcap/pd:latest
    container_name: pd
    ports:
      - "2379:2379"
      - "2380:2380"
    environment:
      - PD_ADVERTISE_CLIENT_URLS=pd:2379
    command:
      - --name=pd
      - --data-dir=/var/lib/pd
      - --client-urls=http://0.0.0.0:2379
      - --peer-urls=http://0.0.0.0:2380
      - --advertise-client-urls=http://pd:2379
      - --advertise-peer-urls=http://pd:2380

  tikv:
    image: pingcap/tikv:latest
    container_name: tikv
    ports:
      - "20160:20160"
    command:
      - --pd=pd:2379
      - --addr=0.0.0.0:20160
      - --advertise-addr=tikv:20160
      - --data-dir=/var/lib/tikv

  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sbtest
      MYSQL_USER: sbtest
      MYSQL_PASSWORD: password

  # A decommenter si vous souhaitez utiliser une architecture AMD64
  # sysbench:
  #   image: severalnines/sysbench:latest
  #   container_name: sysbench
  #   entrypoint: ["tail", "-f", "/dev/null"] # Keep container running
  #   depends_on:
  #     - mysql
  #     - tidb
  #   volumes:
  #     - ./scripts:/scripts
